
name: Midi Time Machine Build

on: [push, pull_request, workflow_dispatch]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container: debian:11

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.2.x'

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y \
          git \
          build-essential \
          libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev \
          libgl1-mesa-dev \
          libfreetype6-dev libfontconfig1-dev \
          libasound2-dev libjack-jackd2-dev libpulse-dev \
          libgtk-3-dev libwebkit2gtk-4.0-dev

    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{runner.temp}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{runner.temp}}/build -j

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: linux-build
        path: |
          ${{runner.temp}}/build/midi-time-machine/midi-time-machine_artefacts/Release
          !${{runner.temp}}/**/*.a

  macos-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15-intel, macos-latest]

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.2.x'

    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{runner.temp}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=11.7

    - name: Build
      run: cmake --build ${{runner.temp}}/build -j

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: macos-${{ matrix.os }}-build
        path: |
          ${{runner.temp}}/build/midi-time-machine/midi-time-machine_artefacts/Release
          !${{runner.temp}}/**/*.a

  windows-build:
    runs-on: windows-latest

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.2.x'

    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{runner.temp}}/build -A x64

    - name: Build
      run: cmake --build ${{runner.temp}}/build --config Release -j

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: windows-build
        path: |
          ${{runner.temp}}/build/midi-time-machine/midi-time-machine_artefacts/Release
          !${{runner.temp}}/**/*.lib
